### ISSUE TITLE
Oversights in example project

### ISSUE THREAD

**Issue by dy0gu** [kravetsone/elysia-remix#1]
First of all, thanks for your work on connecting Elysia with Remix!

I noticed some oversights in the example project you provide by running the quick start command in your README.md.

The most major one is the fact that you were importing `elysia-remix` in a relative manner from the package repository itself, this breaks when running the template command like you instruct, since the example will be cloned alone.

You also run the Vite dev server with the bun `--watch` flag, which causes an infinite hot reload loop due to conflicts with the native Vite HMR.

I will be opening a PR (#2) to fix these bigger issues, I hope you find it helpful!

**Comment by kravetsone** [comment]
Yeah, thanks!
I use relative import for development and forgot remove it later)

And about `--watch` flag, I think we need to find something that narrows the files that the script overloads when changing
