### ISSUE TITLE
URL assets are broken

### ISSUE THREAD

**Issue by andriygm** [kravetsone/elysia-remix#5]
When trying to import an asset as a URL (see https://vitejs.dev/guide/assets#importing-asset-as-url) and use it in a component, the browser throws an error and the image appears as a broken link.

Browser error when loading the page:
```Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/jpeg". Strict MIME type checking is enforced for module scripts per HTML spec.```

Seems to only happen in dev mode.

**Comment by vadolasi** [comment]
Same where

**Comment by wingleeio** [comment]
I'm getting this issue as well
