### ISSUE TITLE
Reading request body within an action causes `ReadableStream has already been used` error

### ISSUE THREAD

**Issue by andriygm** [kravetsone/elysia-remix#9]
When the Remix client makes a request to an action, and the action tries reading the `ReadableStream`, an error is thrown. I believe this is due to the mechanics of `connect-to-web` implementation.

Example:
```ts
fetcher.submit(formData, {
  action: "/route/to/action",
  method: "post",
});
```
```ts
export const action: ActionFunction = async ({ request }) => {
  console.log(await request.formData());
}
```
throws a `ReadableStream has already been used`.

**Comment by andriygm** [comment]
>Did this example work in production?

yes, the issue was only present in dev mode.

I think #10 fixes this problem (previously, original request object was being passed into `connectToWeb`, causing a double body read).

**Comment by kravetsone** [comment]
did u try new version?

**Comment by andriygm** [comment]
yep! seems to be fixed now.
